//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharePointSnapIn.SharePointPeople {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://schemas.microsoft.com/sharepoint/soap/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="SPPrincipalType", Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public enum SPPrincipalType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        User = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DistributionList = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SecurityGroup = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SharePointGroup = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 32,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrincipalInfo", Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    [System.SerializableAttribute()]
    public partial class PrincipalInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNameField;
        
        private int UserInfoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        private bool IsResolvedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SharePointSnapIn.SharePointPeople.PrincipalInfo[] MoreMatchesField;
        
        private SharePointSnapIn.SharePointPeople.SPPrincipalType PrincipalTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AccountName {
            get {
                return this.AccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNameField, value) != true)) {
                    this.AccountNameField = value;
                    this.RaisePropertyChanged("AccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UserInfoID {
            get {
                return this.UserInfoIDField;
            }
            set {
                if ((this.UserInfoIDField.Equals(value) != true)) {
                    this.UserInfoIDField = value;
                    this.RaisePropertyChanged("UserInfoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool IsResolved {
            get {
                return this.IsResolvedField;
            }
            set {
                if ((this.IsResolvedField.Equals(value) != true)) {
                    this.IsResolvedField = value;
                    this.RaisePropertyChanged("IsResolved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public SharePointSnapIn.SharePointPeople.PrincipalInfo[] MoreMatches {
            get {
                return this.MoreMatchesField;
            }
            set {
                if ((object.ReferenceEquals(this.MoreMatchesField, value) != true)) {
                    this.MoreMatchesField = value;
                    this.RaisePropertyChanged("MoreMatches");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public SharePointSnapIn.SharePointPeople.SPPrincipalType PrincipalType {
            get {
                return this.PrincipalTypeField;
            }
            set {
                if ((this.PrincipalTypeField.Equals(value) != true)) {
                    this.PrincipalTypeField = value;
                    this.RaisePropertyChanged("PrincipalType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/", ConfigurationName="SharePointPeople.PeopleSoap")]
    public interface PeopleSoap {
        
        // CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname principalKeys aus Namespace http://schemas.microsoft.com/sharepoint/soap/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/ResolvePrincipals", ReplyAction="*")]
        SharePointSnapIn.SharePointPeople.ResolvePrincipalsResponse ResolvePrincipals(SharePointSnapIn.SharePointPeople.ResolvePrincipalsRequest request);
        
        // CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname searchText aus Namespace http://schemas.microsoft.com/sharepoint/soap/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/SearchPrincipals", ReplyAction="*")]
        SharePointSnapIn.SharePointPeople.SearchPrincipalsResponse SearchPrincipals(SharePointSnapIn.SharePointPeople.SearchPrincipalsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResolvePrincipalsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResolvePrincipals", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public SharePointSnapIn.SharePointPeople.ResolvePrincipalsRequestBody Body;
        
        public ResolvePrincipalsRequest() {
        }
        
        public ResolvePrincipalsRequest(SharePointSnapIn.SharePointPeople.ResolvePrincipalsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class ResolvePrincipalsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SharePointSnapIn.SharePointPeople.ArrayOfString principalKeys;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public SharePointSnapIn.SharePointPeople.SPPrincipalType principalType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool addToUserInfoList;
        
        public ResolvePrincipalsRequestBody() {
        }
        
        public ResolvePrincipalsRequestBody(SharePointSnapIn.SharePointPeople.ArrayOfString principalKeys, SharePointSnapIn.SharePointPeople.SPPrincipalType principalType, bool addToUserInfoList) {
            this.principalKeys = principalKeys;
            this.principalType = principalType;
            this.addToUserInfoList = addToUserInfoList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResolvePrincipalsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResolvePrincipalsResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public SharePointSnapIn.SharePointPeople.ResolvePrincipalsResponseBody Body;
        
        public ResolvePrincipalsResponse() {
        }
        
        public ResolvePrincipalsResponse(SharePointSnapIn.SharePointPeople.ResolvePrincipalsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class ResolvePrincipalsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SharePointSnapIn.SharePointPeople.PrincipalInfo[] ResolvePrincipalsResult;
        
        public ResolvePrincipalsResponseBody() {
        }
        
        public ResolvePrincipalsResponseBody(SharePointSnapIn.SharePointPeople.PrincipalInfo[] ResolvePrincipalsResult) {
            this.ResolvePrincipalsResult = ResolvePrincipalsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchPrincipalsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchPrincipals", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public SharePointSnapIn.SharePointPeople.SearchPrincipalsRequestBody Body;
        
        public SearchPrincipalsRequest() {
        }
        
        public SearchPrincipalsRequest(SharePointSnapIn.SharePointPeople.SearchPrincipalsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class SearchPrincipalsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string searchText;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int maxResults;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public SharePointSnapIn.SharePointPeople.SPPrincipalType principalType;
        
        public SearchPrincipalsRequestBody() {
        }
        
        public SearchPrincipalsRequestBody(string searchText, int maxResults, SharePointSnapIn.SharePointPeople.SPPrincipalType principalType) {
            this.searchText = searchText;
            this.maxResults = maxResults;
            this.principalType = principalType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchPrincipalsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchPrincipalsResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public SharePointSnapIn.SharePointPeople.SearchPrincipalsResponseBody Body;
        
        public SearchPrincipalsResponse() {
        }
        
        public SearchPrincipalsResponse(SharePointSnapIn.SharePointPeople.SearchPrincipalsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class SearchPrincipalsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SharePointSnapIn.SharePointPeople.PrincipalInfo[] SearchPrincipalsResult;
        
        public SearchPrincipalsResponseBody() {
        }
        
        public SearchPrincipalsResponseBody(SharePointSnapIn.SharePointPeople.PrincipalInfo[] SearchPrincipalsResult) {
            this.SearchPrincipalsResult = SearchPrincipalsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PeopleSoapChannel : SharePointSnapIn.SharePointPeople.PeopleSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PeopleSoapClient : System.ServiceModel.ClientBase<SharePointSnapIn.SharePointPeople.PeopleSoap>, SharePointSnapIn.SharePointPeople.PeopleSoap {
        
        public PeopleSoapClient() {
        }
        
        public PeopleSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PeopleSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeopleSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeopleSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharePointSnapIn.SharePointPeople.ResolvePrincipalsResponse SharePointSnapIn.SharePointPeople.PeopleSoap.ResolvePrincipals(SharePointSnapIn.SharePointPeople.ResolvePrincipalsRequest request) {
            return base.Channel.ResolvePrincipals(request);
        }
        
        public SharePointSnapIn.SharePointPeople.PrincipalInfo[] ResolvePrincipals(SharePointSnapIn.SharePointPeople.ArrayOfString principalKeys, SharePointSnapIn.SharePointPeople.SPPrincipalType principalType, bool addToUserInfoList) {
            SharePointSnapIn.SharePointPeople.ResolvePrincipalsRequest inValue = new SharePointSnapIn.SharePointPeople.ResolvePrincipalsRequest();
            inValue.Body = new SharePointSnapIn.SharePointPeople.ResolvePrincipalsRequestBody();
            inValue.Body.principalKeys = principalKeys;
            inValue.Body.principalType = principalType;
            inValue.Body.addToUserInfoList = addToUserInfoList;
            SharePointSnapIn.SharePointPeople.ResolvePrincipalsResponse retVal = ((SharePointSnapIn.SharePointPeople.PeopleSoap)(this)).ResolvePrincipals(inValue);
            return retVal.Body.ResolvePrincipalsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharePointSnapIn.SharePointPeople.SearchPrincipalsResponse SharePointSnapIn.SharePointPeople.PeopleSoap.SearchPrincipals(SharePointSnapIn.SharePointPeople.SearchPrincipalsRequest request) {
            return base.Channel.SearchPrincipals(request);
        }
        
        public SharePointSnapIn.SharePointPeople.PrincipalInfo[] SearchPrincipals(string searchText, int maxResults, SharePointSnapIn.SharePointPeople.SPPrincipalType principalType) {
            SharePointSnapIn.SharePointPeople.SearchPrincipalsRequest inValue = new SharePointSnapIn.SharePointPeople.SearchPrincipalsRequest();
            inValue.Body = new SharePointSnapIn.SharePointPeople.SearchPrincipalsRequestBody();
            inValue.Body.searchText = searchText;
            inValue.Body.maxResults = maxResults;
            inValue.Body.principalType = principalType;
            SharePointSnapIn.SharePointPeople.SearchPrincipalsResponse retVal = ((SharePointSnapIn.SharePointPeople.PeopleSoap)(this)).SearchPrincipals(inValue);
            return retVal.Body.SearchPrincipalsResult;
        }
    }
}
