//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharePointSnapIn.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharePointSnapIn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An eine Dokumentbibliothek kann nichts angefügt werden. ähnelt.
        /// </summary>
        internal static string AppendLibraryUnsupported {
            get {
                return ResourceManager.GetString("AppendLibraryUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anhängen? ähnelt.
        /// </summary>
        internal static string AppendModeField {
            get {
                return ResourceManager.GetString("AppendModeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Format des Attributes &apos;{0}&apos;  ist ungültig: {1} ähnelt.
        /// </summary>
        internal static string AttributeFormatInvalid {
            get {
                return ResourceManager.GetString("AttributeFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nein ähnelt.
        /// </summary>
        internal static string BooleanFalseValue {
            get {
                return ResourceManager.GetString("BooleanFalseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ja ähnelt.
        /// </summary>
        internal static string BooleanTrueValue {
            get {
                return ResourceManager.GetString("BooleanTrueValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eine Einstellung hat sich geändert. Bitte überprüfen Sie die Werte erneut. ähnelt.
        /// </summary>
        internal static string ChangeDuringSubmit {
            get {
                return ResourceManager.GetString("ChangeDuringSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inhaltstyp ähnelt.
        /// </summary>
        internal static string ContentTypeField {
            get {
                return ResourceManager.GetString("ContentTypeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;leer&gt; ähnelt.
        /// </summary>
        internal static string EmptySelection {
            get {
                return ResourceManager.GetString("EmptySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - [{0}] ähnelt.
        /// </summary>
        internal static string ExcludeSelectionFormat {
            get {
                return ResourceManager.GetString("ExcludeSelectionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der SharePoint Feld-Typ &apos;{0}&apos; wird nicht unterstützt. ähnelt.
        /// </summary>
        internal static string FieldTypeUnsupported {
            get {
                return ResourceManager.GetString("FieldTypeUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eine Datei mit diesem Namen existiert bereits. ähnelt.
        /// </summary>
        internal static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dateiname ähnelt.
        /// </summary>
        internal static string FileNameField {
            get {
                return ResourceManager.GetString("FileNameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zielordner ähnelt.
        /// </summary>
        internal static string FolderField {
            get {
                return ResourceManager.GetString("FolderField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die + {0} ähnelt.
        /// </summary>
        internal static string IncludeSelectionFormat {
            get {
                return ResourceManager.GetString("IncludeSelectionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Dateiname enthält ungültige Zeichen.
        ///({0} sind nicht erlaubt.) ähnelt.
        /// </summary>
        internal static string InvalidCharsInFileName {
            get {
                return ResourceManager.GetString("InvalidCharsInFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eintrag ähnelt.
        /// </summary>
        internal static string ListItemField {
            get {
                return ResourceManager.GetString("ListItemField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Liste &apos;{0}&apos; erlaubt keine Attachments oder Dokumente. ähnelt.
        /// </summary>
        internal static string ListNotAllowingFiles {
            get {
                return ResourceManager.GetString("ListNotAllowingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die spezielle Liste &apos;{0}&apos; wird nicht für Nachschlagefelder unterstützt. ähnelt.
        /// </summary>
        internal static string LookupListUnsupported {
            get {
                return ResourceManager.GetString("LookupListUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Attribut &apos;{0}&apos; hat einen ungültigen Nachschlageprefix. ähnelt.
        /// </summary>
        internal static string LookupPrefixInvalid {
            get {
                return ResourceManager.GetString("LookupPrefixInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wurden zuviele Einträge gewählt. ähnelt.
        /// </summary>
        internal static string LookupValueTooLong {
            get {
                return ResourceManager.GetString("LookupValueTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Für den_die Benutzer_in oder Gruppe &apos;{0}&apos; wurden mehrfache Werte gefunden. ähnelt.
        /// </summary>
        internal static string MultipleUserMatchesFound {
            get {
                return ResourceManager.GetString("MultipleUserMatchesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wurden keine passenden Inhaltstypen gefunden. ähnelt.
        /// </summary>
        internal static string NoMatchingContentTypes {
            get {
                return ResourceManager.GetString("NoMatchingContentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Wert muss ein gültiges numerisches Format aufweisen.
        ///Beispiel: {0} ähnelt.
        /// </summary>
        internal static string NumericFormatInvalid {
            get {
                return ResourceManager.GetString("NumericFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Wert muss über {0} sein. ähnelt.
        /// </summary>
        internal static string NumericMustBeAboveMinimum {
            get {
                return ResourceManager.GetString("NumericMustBeAboveMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Wert muss unter {0} sein. ähnelt.
        /// </summary>
        internal static string NumericMustBeBelowMaximum {
            get {
                return ResourceManager.GetString("NumericMustBeBelowMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Dateipfad &apos;{0}&apos; liegt außerhalb des Webpfades &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string PathOutsideWeb {
            get {
                return ResourceManager.GetString("PathOutsideWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Attribute oder Element &apos;{0}&apos; fehlt. ähnelt.
        /// </summary>
        internal static string RequiredAttributeOrElementMissing {
            get {
                return ResourceManager.GetString("RequiredAttributeOrElementMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es muss ein Wert für &apos;{0}&apos; eingegeben werden. ähnelt.
        /// </summary>
        internal static string RequiredFieldMissing {
            get {
                return ResourceManager.GetString("RequiredFieldMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der angegebene Ausgangsordner &apos;{0}&apos; wurde nicht gefunden. ähnelt.
        /// </summary>
        internal static string RootFolderNotFound {
            get {
                return ResourceManager.GetString("RootFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Wert muss ein gültiger, absoluter URL sein.
        ///Beispiel: http://www.example.com/page.htm ähnelt.
        /// </summary>
        internal static string UrlFormatInvalid {
            get {
                return ResourceManager.GetString("UrlFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der_die Benutzer_in oder die Gruppe &apos;{0}&apos; konnte nicht auflösen. ähnelt.
        /// </summary>
        internal static string UserNotResolved {
            get {
                return ResourceManager.GetString("UserNotResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Durch Gruppen limitierte Benutzerfelder werden nicht unterstützt. ähnelt.
        /// </summary>
        internal static string UserSelectionScopeUnsupported {
            get {
                return ResourceManager.GetString("UserSelectionScopeUnsupported", resourceCulture);
            }
        }
    }
}
